### ISSUE TITLE
Not able to deploy bookshop sample with multi-tenancy to SAP BTP

### ISSUE THREAD

**Issue by Hank1986** [cap-js/docs#382] opened 2023-08-28 07:31 UTC
Hello Team,

When i am following the steps to create the bookshop sample application with multi-tenancy enabled, everything works perfect in my local. However, when i am try to deploy it to my BTP global account, i got the below error messages.
Error messages from bookshop-mtx application
![image](https://github.com/cap-js/docs/assets/24907480/468bfa45-6b05-440f-936f-1b63c174b11f)
Error messages from bookshop-srv application
![image](https://github.com/cap-js/docs/assets/24907480/abddbf15-0d68-4a37-9429-f1eafd3ac0af)

Would you please help to figure out is there any step is missing from my side, or this is still not support by @sap/cds-mtxs?

Best Regards,
Hank.

**Comment by renejeglinsky** [comment] 2023-08-28 11:44
Hi @Hank1986,

from your second error, I created a fix in our samples repository as needed since [June](https://cap.cloud.sap/docs/releases/jun23#use-cds-serve-as-start-script).

Do you use the latest `@sap/cds-dk` package?
We found, that the command `cds add hana --for production` is missing in the multitenancy guide. Could you pls give that a try and see if that fixes your error?

All the best,
René

**Comment by Hank1986** [comment] 2023-08-29 06:50
> 

Hello Rene,

Actually, I setup my sample project with node18 and latest cds, cds-dk and npm. Please refer below screenshot for more details.
<img width="552" alt="image" src="https://github.com/cap-js/docs/assets/24907480/f80da93a-079d-40ee-bf12-c3e59f5d1af6">


Best Regards,
Hank.

**Comment by Hank1986** [comment] 2023-08-29 08:31
> Hi @Hank1986,
> 
> from your second error, I created a fix in our samples repository as needed since [June](https://cap.cloud.sap/docs/releases/jun23#use-cds-serve-as-start-script).
> 
> Do you use the latest `@sap/cds-dk` package? We found, that the command `cds add hana --for production` is missing in the multitenancy guide. Could you pls give that a try and see if that fixes your error?
> 
> All the best, René

Hello Rene,

After updated the script from 'cds run' to 'cds-serve' the application bookshop-srv started successful. However, the application bookshop-mtx still ran into the same error.
Logs from application bookshop-srv.
<img width="943" alt="image" src="https://github.com/cap-js/docs/assets/24907480/c2c13b73-47ef-4200-8be3-e6a10484ee79">
Logs from application bookshop-mtx
<img width="1163" alt="image" src="https://github.com/cap-js/docs/assets/24907480/6a1fa917-b27c-4c87-a458-8f66e9776f4b">

Best Regards,
Hank.

**Comment by Hank1986** [comment] 2023-08-31 09:27
> Hi @Hank1986 ,
> 
> did you execute `cds add hana --for production` in your project?

Hi @renejeglinsky ，

Yes, the 'cds add hana --for production' was executed in my project. And below is the package.json file in my project.
<img width="456" alt="image" src="https://github.com/cap-js/docs/assets/24907480/e8398a74-4bda-4416-92fd-f297a5b98d92">


Best Regards,
Hank.

**Comment by renejeglinsky** [comment] 2023-08-31 19:19
Hi Hank,

Did you use our bookshop from our [cap samples](https://github.com/SAP-samples/cloud-cap-samples)?
If so, the deployment of it is always challenging, due to the monorepo setup. In that case, please start with a fresh bookshop as described in the guide.

All the best,
René

**Comment by Hank1986** [comment] 2023-09-05 07:49
> Hi Hank,
> 
> Did you use our bookshop from our [cap samples](https://github.com/SAP-samples/cloud-cap-samples)? If so, the deployment of it is always challenging, due to the monorepo setup. In that case, please start with a fresh bookshop as described in the guide.
> 
> All the best, René

Hi @renejeglinsky,

Yes, i use the bookshop from cap samples by following the steps which mentioned in document. Deploy as Multitenant SaaS Application https://cap.cloud.sap/docs/guides/deployment/as-saas#add-multitenancy.

The same error even i retried serval times from scratch.

Best Regards,
Hank.

**Comment by renejeglinsky** [comment] 2023-09-15 08:50
Hi @Hank1986 ,

I went through the steps today and encountered no issue. The only difference I could spot, is that your sidecar uses `jwt-auth` and mine `jwt`. I was using a trial account which is also different from your setup. Though I'm not really sure what causes your issue.

**Comment by renejeglinsky** [comment] 2023-09-26 13:16
Hi @Hank1986 ,

In the meantime, did you succeed in running your app?

**Comment by Hank1986** [comment] 2023-09-27 09:16
> Hi @Hank1986 ,
> 
> In the meantime, did you succeed in running your app?

Hi @renejeglinsky ,

Unfortunately, it's still not working to me. Not sure what's wrong here.

Best Regards,
Hank.

**Comment by renejeglinsky** [comment] 2023-11-03 08:09
Hi Hank,

would you want to give it another try with recent versions? Or should we close this issue? Probably it makes more sense to ask this question on the [community](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce) and provide a link to your repo to be able to reproduce it.

**Comment by renejeglinsky** [comment] 2023-11-22 11:28
I guess we won't find a solution here. I'm sorry. Therefore I'm closing this issue.

**Closed by renejeglinsky** 2023-11-22 11:28 UTC
